# Generated by Django 2.1.1 on 2018-10-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correoElectronico', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
                ('tema', models.IntegerField(default=0)),
                ('moneda', models.CharField(max_length=5)),
                ('tipoDeCuenta', models.IntegerField(default=0)),
            ],
        ),
    ]
