# Generated by Django 2.1.1 on 2018-11-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save', '0003_categoria_egreso_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='ahorro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ahorro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
