# Generated by Django 2.1.1 on 2018-12-05 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('save', '0004_auto_20181104_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlEgreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='save.Categoria')),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='moneda',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tema',
        ),
        migrations.AddField(
            model_name='controlegreso',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='save.Usuario'),
        ),
    ]
